config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :details, except: [:index, :show] do
    resources :reviews, only: [ :new, :create, :index ]
    resources :exams , only: [ :new, :create ]
  end

  resources :exams, only: [ :edit, :update, :destroy, :index, :show ] do
    resources :answers, only: [ :new, :create ]
  end

  resources :answers, only: [ :index ,:show]

  resources :reviews, only: [ :edit, :update, :destroy, :index ]

  resources :courses do
    resources :details, only: [:index, :show]
  end

  resources :memberships
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exam
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :details, dependent: :destroy
  has_one_attached :photo
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :course
  has_one :exam, dependent: :destroy
  has_many :reviews,dependent: :destroy
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :detail
  has_many :answers
end

app/models/membership.rb
class Membership < ApplicationRecord
  has_many :users
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :detail
  belongs_to :user
  has_many :users
  has_many :details
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[ edit update show destroy ]
  before_action :set_exam, only: %i[ new create]
  def index
    @answers = current_user.answers
  end

  def show
    @exam = @answer.exam
    @detail = @exam.detail
  end

  def new
    @answer = Answer.new()
    @detail = @exam.detail
  end

  def create
    answer = Answer.new(answer_params)
    answer.exam = @exam
    answer.user = current_user
    answer.score = 0
    answer.score += 1 if @exam.answer_solution == answer.r1
    answer.score += 1 if @exam.r2 == answer.r2
    answer.score += 1 if @exam.r3 == answer.r3
    answer.score += 1 if @exam.r4 == answer.r4
    answer.approved = answer.score >= 3
    answer.save
    redirect_to answer_path(answer)
  end

  def edit
  end

  def update
    if @answer.update(answer_params)
      redirect_to answer_path(@answer)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to answer_path
  end

  private

  def answer_params
    params.require(:answer).permit( :r1, :r2, :r3, :r4 )
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_exam
    @exam = Exam.find(params[:exam_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ edit update show destroy ]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
  # @course.user = current_user
     if @course.save
       redirect_to courses_path
     else
       render :new
     end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to course_path(@course)
    else
      render :edit
    end
  end

  def destroy
    if @course.destroy
      redirect_to courses_path
    end
  end

  private

  def course_params
    params.require(:course).permit(:name, :description, :photo)
  end

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  def index
    @details = Detail.where(course_id: params[:course_id])
    @course = @details.first.course
    # @details = Detail.all
  end

  def show
    @detail = Detail.find(params[:id])
    @course = @detail.course
    @review = Review.new
  end

  def new
    @course = Course.find(params[:course_id])
    @detail = Detail.new
  end

  def create
    @detail = Detail.new(detail_params)
    @detail.user = current_user
    # we need `restaurant_id` to associate detail with corresponding restaurant
    @course = Course.find(params[:course_id])
    @detail.course = @course
    if @detail.save
      redirect_to course_path(@course)
    else
      render :new
    end
  end

  def edit
    @detail = Detail.find(params[:id])
  end

  def update
    @detail = Detail.find(params[:id])
    if @detail.update(detail_params)
      redirect_to course_path
    else
      render :edit
    end
  end

  def destroy
    @detail = detail.find(params[:id])
    @detail.destroy
    redirect_to course_path(@detail.course)
  end

  private

  def review_params
    params.require(:detail).permit(:name, :content)
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: %i[ edit update show destroy ]
  # before_action :set_detail, only: %i[ create ]
  def index
    @answer = Answer.new
    @exams = Exam.where(detail_id: params[:detail_id])
    @detail = Detail.find(params[:detail_id])
  end

  def show
  end

  def new
    @exam = Exam.new
    @detail = Detail.find(params[:detail_id])
    @exams = Exam.where(detail_id: params[:detail_id])
  end

  def create
    @detail = Detail.find(params[:detail_id])
    @exam = Exam.new(exam_params)
    @exam.detail = @detail
    if @exam.save
      redirect_to detail_exams_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @exam.update(exam_params)
      redirect_to exam_path(@exam)
    else
      render :edit
    end
  end

  def destroy
    @exam.destroy
    redirect_to exam_path
  end

  private

  def exam_params
    params.require(:exam).permit(:ru1, :ru2, :ru3, :ru4)
  end

  def set_exam
    @exam = Exam.find(params[:id])
  end

  # def set_detail
  #   @detail = Detail.find(params[:id])
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
    @detail = @reviews.first.detail
  end

  def new
    @detail = Detail.find(params[:detail_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    # we need `restaurant_id` to associate review with corresponding restaurant
    @detail = Detail.find(params[:detail_id])
    @review.detail = @detail
    if @review.save
      redirect_to course_detail_path(@detail.course, @detail)

    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to detail_path(@review.detail)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/index.html.erb
<div class="container exam-admi">
  <h2></h2>
  <% @answers.each do |answer| %>
    <%=  answer.approved %>
  <% end %>
</div>

app/views/answers/new.html.erb
<br>
<div class="container">
  <h2 style="text-align:center;"><strong><%= @detail.name %></strong></h2>
  <br>
  <br>
  <div class="row">
    <div class="col-8 mx-auto">
      <%= simple_form_for @answer, method: :post, url: exam_answers_path(@exam) do |f| %>
        <div class="card-exam pb-3 ">
          <p class="pb-1"><strong><%= @exam.question %></strong><br></p>
          a.- <%= @exam.answerA %><br>
          b.- <%= @exam.answerB %><br>
          c.- <%= @exam.answerC %><br>
          <%= f.input :r1, label: 'Answer No1' , collection: [
            'a', 'b', 'c']%>
        </div>
        <div class="card-exam pb-3">
          <p class="pb-1"><strong><%= @exam.p2 %></strong><br></p>
          a.- <%= @exam.r21 %><br>
          b.- <%= @exam.r22 %><br>
          c.- <%= @exam.r23 %><br>
          <%= f.input :r2, label: 'Answer No2' , collection: [
            'a', 'b', 'c']%>
        </div>
        <div class="card-exam pb-3">
          <p class="pb-1"><strong><%= @exam.p3 %></strong><br></p>
          a.- <%= @exam.r31 %><br>
          b.- <%= @exam.r32 %><br>
          c.- <%= @exam.r33 %><br>
          <%= f.input :r3, label: 'Answer No3', collection: [
            'a', 'b', 'c']%>
        </div>
        <div class="card-exam pb-3">
          <p class="pb-1"><strong><%= @exam.p4 %></strong><br></p>
          a.- <%= @exam.r41 %><br>
          b.- <%= @exam.r42 %><br>
          c.- <%= @exam.r43 %><br>
          <%= f.input :r4, label: 'Answer No4', collection: [
            'a', 'b', 'c']%>
        </div>
        <%= f.submit "Enviar", class: "btn btn-outline-dark pb-2 m-3" %> <%= link_to 'Volver', course_detail_path(@detail.course, @detail), class: "btn btn-outline-dark p-2 m-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/answers/show.html.erb
<br>
<div class="container" style="position:relative">
  <h2 style="text-align:center;"><strong><%= @detail.name %></strong></h2>
  <div class="bg-warning rounded d-flex align-items-center justify-content-center fw-bold" style="position:absolute;height:3.5%;width:6%;font-size:2vw;top:.5%;left:76%"><%= (@answer.score / 4 * 100).to_i %>%</div>
  <br>
  <br>
  <div class="row">
    <div class="col-8 mx-auto">
      <%= simple_form_for @answer, method: :post, url: exam_answers_path(@exam) do |f| %>
        <div class="card-exam pb-3 ">
          <p class="pb-1"><strong><%= @exam.question %></strong><br></p>
          a.- <%= @exam.answerA %><br>
          b.- <%= @exam.answerB %><br>
          c.- <%= @exam.answerC %><br>
          <%= f.input :r1, label: 'Answer No1' , collection: [
            'a', 'b', 'c'], input_html: { disabled: true, class: (@exam.answer_solution == @answer.r1 ? "is-valid" : "is-invalid")  }%>
        </div>
        <div class="card-exam pb-3">
          <p class="pb-1"><strong><%= @exam.p2 %></strong><br></p>
          a.- <%= @exam.r21 %><br>
          b.- <%= @exam.r22 %><br>
          c.- <%= @exam.r23 %><br>
          <%= f.input :r2, label: 'Answer No2' , collection: [
            'a', 'b', 'c'] , input_html: { disabled: true, class: (@exam.r2 == @answer.r2 ? "is-valid" : "is-invalid") }%>
        </div>
        <div class="card-exam pb-3">
          <p class="pb-1"><strong><%= @exam.p3 %></strong><br></p>
          a.- <%= @exam.r31 %><br>
          b.- <%= @exam.r32 %><br>
          c.- <%= @exam.r33 %><br>
          <%= f.input :r3, label: 'Answer No3', collection: [
            'a', 'b', 'c'] , input_html: { disabled: true, class: (@exam.r3 == @answer.r3 ? "is-valid" : "is-invalid") }%>
        </div>
        <div class="card-exam pb-3">
          <p class="pb-1"><strong><%= @exam.p4 %></strong><br></p>
          a.- <%= @exam.r41 %><br>
          b.- <%= @exam.r42 %><br>
          c.- <%= @exam.r43 %><br>
          <%= f.input :r4, label: 'Answer No4', collection: [
            'a', 'b', 'c'] , input_html: { disabled: true, class: (@exam.r4 == @answer.r4 ? "is-valid" : "is-invalid") }%>
        </div>
      <% end %>
      <%= link_to 'Regresar', course_detail_path(@detail.course, @detail), class: "btn btn-outline-dark p-2 m-3" %>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<%= simple_form_for(@course) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/courses/index.html.erb
<%# <head>
  	<link rel="stylesheet" href="css/style.css">
	<title>Creativa</title>
	<meta name="description" content="Creativa Lab">
	<meta charset="utf-8">
	<script src="https://kit.fontawesome.com/cba6117f5a.js" crossorigin="anonymous"></script>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@200;300;600;700&display=swap" rel="stylesheet">

</head> %>

<body>
  <div class="course-banner d-flex">
    <div class="banner-1">
      <div class="index-banner">
        <h1 style="text-align:center; color:white;">¡Hola <%= current_user.name %>!</h1>
        <p style= "font-size:22px; text-align:center;" >Inicia hoy aprendiendo<br> habilidades digitales para las<br> organizaciones del futuro.</p>
      </div>
<br>
      <div style="padding-top:5px;" class="img-icons">
        <div class="card-img">
          <%= image_tag "landin.png", class:"img5" %>
          <p>Landing</p>
        </div>
        <div class="card-img">
          <%= image_tag "brand.png", class:"img5" %>
          <p>Branding</p>
        </div>
        <div class="card-img">
          <%= image_tag "design.png", class:"img5" %>
          <p>Design</p>
        </div>
      </div>
    </div>

    <div class="img-banner">
      <%= image_tag "chicab.jpg", class:"img4" %>
    </div>
  </div>
<br>
<div class="boton">
  <p style= "font-size:40px;"><strong>Cursos</strong></p>
</div>

<div class="container">
  <div class="cards-c">
    <% @courses.each do |course| %>
        <div class="cards-container mb-4">
          <% if course.photo.attached?%>
          <%= cl_image_tag course.photo.key, height: 160, width: 158, crop: :fill, styles: "object-fit: cover" %>
            <% end %>
          <div class="cards-2">
              <h3 style= "font-size:22px; font-family: 'Outfit', sans-serif;"><%= course.name %></h3>
              <div class="mt-4">
                <%= link_to 'Empezar', course_path(course), class: "btn btn-outline-dark" %>
              </div>
            </div>
        </div>
    <% end %>
  </div>
</div>

  <div class="flex-item mb-5">
    <div class="banner-2">
      <div class="last-end">
        <p style= "font-size:20px;">Nuestro team siempre<br>
        está listo para<br>
        ayudarte</p>
        <br>
        <p style= "font-size:20px;">¿Estás listo para<br>
        potenciar tus habilidades?</p>
      </div>
    </div>
    <div class="ban-2">
      <%= image_tag "fundadoras.png", class:"img7" %>
      <!-- <%= image_tag "chic.jpg", class:"img7" %> -->
    </div>
  </div>

app/views/courses/new.html.erb
<%= simple_form_for(@course) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/courses/show.html.erb
<div class='container mt-5 pt-5'>
<div class="courses-showw">
  <div class="row">
      <div class="">
        <h1 style="font-size: 3.1rem;"><%= @course.name %></h1>
        <br>
        <p class="" style="margin-bottom: 2.5rem">Descripción: <%= @course.description %></p>
        <p></p>
      </div>

      <div class="col-4">
          <%= cl_image_tag @course.photo.key, width: "300" %>
      </div>
    </div>

      <div class="container" style="margin-top: 50px; margin-left: -50px;">
        <%= link_to 'Ver módulos', course_details_path(@course), class: "btn btn-outline-dark mx-4" %>
        <!-- <%= link_to 'Nuevo curso', new_course_path(@course), class: "btn btn-primary" %> -->
        <%= link_to 'Volver', courses_path, class: "btn btn-outline-dark" %>
      </div>
</div>

</div>




          <!-- <%# <%= link_to 'Editar', edit_course_path(@course), class: "btn btn-success" %>
          <%# <%= link_to 'Eliminar', course_path(@course), class: "btn btn-primary", method: :delete %> -->
          <!-- <%# <%= link_to 'Rentar', new_course_path(@course), class: "btn btn-primary" %> -->

app/views/details/index.html.erb
<div class="container container-details">
  <h2 style = "color: black; margin-top:75px; text-align:center;"><%= @course.name %></h2>
  <div class="cards-detail">
  <% @details.each do |detail| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= detail.video_url %>)">

      <%= link_to detail.name, course_detail_path(detail.course,detail), class: "btn btn-outline-light", style: "font-size:20px;"%>
    </div>
  <% end %>

  </div>
  <div class = "container" style = "margin-bottom: 85px; margin-top: 30px; padding-left: 0px;">
    <%= link_to 'Volver', course_path(@course), class: "btn btn-outline-dark" %>
  </div>

</div>

app/views/details/show.html.erb
<div class="container-modulo">
  <h2 style = "color: black; margin-bottom: 30px; "><%= @course.name %></h2>
  <div class="comentario">
    <div class="row">
      <div class = "col-2">
        <h5><%= link_to @course.details.first.name, course_detail_path(@detail.course,@detail.course.details.first), class: "btn btn-outline-dark hola" %></h5>
        <h5><%= link_to @course.details.second.name, course_detail_path(@detail.course,@detail.course.details.second), class: "btn btn-outline-dark hola" %></h5>
        <h5><%= link_to @course.details.third.name, course_detail_path(@detail.course,@detail.course.details.third), class: "btn btn-outline-dark hola" %></h5>
      </div>

      <div class = "col-6">
        <iframe width="580" height="440" src=<%= @detail.content %> title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class = "col-4">
        <div class="chat-container">
          <div class="chat-header">
            <h2 style="color: black;"><i class="fab fa-slack-hash"></i><strong> Comentarios</strong></h2>
          </div>
          <div class="chat-conversations overflow-auto">
            <% @detail.reviews.each do |review| %>
              <div class="message">
                <img src="https://media.istockphoto.com/illustrations/email-icon-special-blue-square-button-illustration-id827639136?k=20&m=827639136&s=612x612&w=0&h=aMH7VAx9e7f3PmhdrYJ-8Kyt9QLFsurtcGHPJJz2uek=" alt="">
                <div class="message-content">
                  <p><strong><%= review.user.name %></strong></p>
                  <p><%= review.content %></p>
                </div>
              </div>
            <% end %>
            <div class="chat-input">
                <%= simple_form_for [ @detail, @review ] do |f| %>
                  <%= f.input :content, label: "Comentar" %>
                  <%= f.submit "Enviar", class: "btn btn-outline-dark" %>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div style = "margin-top: 50px;", class="d-flex justify-content-between cuestionario">
    <%= link_to "Volver" , course_details_path(@course), class:"btn btn-outline-dark"%>
    <%= link_to "Cuestionario" , new_exam_answer_path(@detail.exam), class:"btn btn-outline-dark"%>
    <%# <%= link_to "Cuestionario" , new_exam_answer_path(@detail.exams.first), class:"btn btn-primary"%>
  </div>
</div>

app/views/exams/index.html.erb
<div class="container exam-admi ">
  <div class="row">
    <div class="col-8 mx-auto">
      <h5 class="pb-3"><strong><%= @detail.name %></strong></h5>
      <% @exams.each do |exam| %>
        <div class="card-exams pb-3">
          <p><strong><%= exam.question %></strong></p>
          <%= simple_form_for [exam, @answer] do |f| %>
            <%= f.input :answer, label:"Selecciona tu respuesta", as: :radio_buttons, collection: [
              exam.answerA,
              exam.answerB,
              exam.answerB]%>
          <% end %>
        </div>
        <div class=" card-exams pb-3">
          <p><strong><%= exam.p2 %></strong></p>
          <%= simple_form_for [exam, @answer] do |f| %>
            <%= f.input :answer, label:"Selecciona tu respuesta", as: :radio_buttons, collection: [
              exam.r21,
              exam.r22,
              exam.r23]%>
          <% end %>
        </div>
        <div class=" card-exams pb-3">
          <p><strong><%= exam.p3 %></strong></p>
          <%= simple_form_for [exam, @answer] do |f| %>
            <%= f.input :answer, label:"Selecciona tu respuesta", as: :radio_buttons, collection: [
              exam.r31,
              exam.r32,
              exam.r33]%>
          <% end %>
        </div>
        <div class="card-exams pb-5">
          <p><strong><%= exam.p4 %></strong></p>
          <%= simple_form_for [exam, @answer] do |f| %>
            <%= f.input :answer, label:"Selecciona tu respuesta", as: :radio_buttons, collection: [
              exam.r41,
              exam.r42,
              exam.r43]%>
          <% end %>
        </div>
        <%= exam.answer_solution %>
      <% end %>
      <%= link_to 'Enviar', detail_exams_path, class: "btn btn-outline-primary p-2 m-3" %>
      <%# <button type="submit" class="btn btn-outline-primary p-2 m-3 ">Enviar</button> %>
      <%= link_to 'Regresar', course_detail_path(@detail.course, @detail), class: "btn btn-outline-primary p-2 m-3" %>
    </div>
  </div>
</div>

app/views/exams/new.html.erb
<br>
<div class="container">
  <h2 style="text-align:center;"><strong><%= @detail.name %></strong></h2>
  <br>
  <br>
  <div class="row">
    <div class="col-8 mx-auto">
      <% @exams.each do |exam| %>
        <div class="card-exam pb-3 ">
          <p class="pb-1"><strong><%= exam.question %></strong><br></p>
          a.- <%= exam.answerA %><br>
          b.- <%= exam.answerB %><br>
          c.- <%= exam.answerC %><br>
          <%= simple_form_for [@exam] do |f| %>
            <%= f.input :answer_solution, label: "", prompt: "Selecciona tu respuesta", collection: [
              'a', 'b', 'c']%>
          <%# end %>
        </div>
        <div class="card-exam pb-3">
          <p class="pb-1"><strong><%= exam.p2 %></strong><br></p>
          a.- <%= exam.r21 %><br>
          b.- <%= exam.r22 %><br>
          c.- <%= exam.r23 %><br>
          <%#= simple_form_for [@exam] do |f| %>
            <%= f.input :r2, prompt: "Selecciona tu respuesta", collection: [
              'a', 'b', 'c']%>
          <%# end %>
        </div>
        <div class="card-exam pb-3">
          <p class="pb-1"><strong><%= exam.p3 %></strong><br></p>
          a.- <%= exam.r31 %><br>
          b.- <%= exam.r32 %><br>
          c.- <%= exam.r33 %><br>
          <%#= simple_form_for [@exam] do |f| %>
            <%= f.input :r3, prompt: "Selecciona tu respuesta", collection: [
              'a', 'b', 'c']%>
          <%# end %>
        </div>
        <div class="card-exam pb-3">
          <p class="pb-1"><strong><%= exam.p4 %></strong><br></p>
          a.- <%= exam.r41 %><br>
          b.- <%= exam.r42 %><br>
          c.- <%= exam.r43 %><br>
          <%#= simple_form_for [@exam] do |f| %>
            <%= f.input :r4, prompt: "Selecciona tu respuesta", collection: [
              'a', 'b', 'c']%> 
          <%# end %>
        </div>
        <% end %>
      <% end %>
      <%# <button type="submit" class="btn btn-outline-primary p-2 m-3 ">Enviar</button> %>
    </div>
    <%= link_to 'Volver', course_detail_path(@detail.course, @detail), class: "btn btn-outline-dark" %> Hola <%= f.submit "Enviar", class: "btn btn-outline-dark" %>
  </div>
</div>

app/views/exams/show.html.erb
<div class="container my-5">
  <%= @exam.question %>
  <%= @exam.answerA %>
  <%= @exam.answerB %>
  <%= @exam.answerC %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Creativalabf</title>
      <meta property="og:title" content="Creativa Lab">
      <meta property="og:image" content="facebook-card.jpg">
      <meta property="og:description" content="Acelerador de carrera para mujeres no tech">
      <meta property="og:site_name" content="Creativa Lab"/>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script type="text/javascript" src="Scripts/jquery-2.1.1.min.js"></script>

  <!-- app/views/layouts/application.html.erb -->
  <%= favicon_link_tag %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
	  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@200;300;600;700&display=swap" rel="stylesheet">

  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>


  </body>
</html>

app/views/reviews/index.html.erb
<br>
<br>
<br>
<br>
<br>
<div class="card">
  <% @reviews.each  do |review| %>
    <%= review.content %>
  <% end %>
</div>
<%= link_to "Back to Detail", detail_path(@detail), class: "btn btn-success" %>

app/views/reviews/new.html.erb
<div class="container">
  <%= simple_form_for [ @detail, @review ] do |f| %>
    <%= f.input :content %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>